### ISSUE TITLE
Some problem with irc chat line break

### ISSUE THREAD

**Issue by d-dd** [d-dd/Yukari#26]
Some encoding error, need to reproduce again for error message.

**Comment by d-dd** [comment]
Unhandled Error
Traceback (most recent call last):
  File "/home/dd/.virtualenvs/yuka/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 220, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/home/dd/.virtualenvs/yuka/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2430, in dataReceived
    basic.LineReceiver.dataReceived(self, data.replace('\r', ''))
  File "/home/dd/.virtualenvs/yuka/local/lib/python2.7/site-packages/twisted/protocols/basic.py", line 571, in dataReceived
    why = self.lineReceived(line)
  File "/home/dd/.virtualenvs/yuka/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2438, in lineReceived
    self.handleCommand(command, prefix, params)
--- <exception caught here> ---
  File "/home/dd/.virtualenvs/yuka/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 2482, in handleCommand
    method(prefix, params)
  File "/home/dd/.virtualenvs/yuka/local/lib/python2.7/site-packages/twisted/words/protocols/irc.py", line 1939, in irc_PRIVMSG
    self.privmsg(user, channel, message)
  File "/home/dd/mikumonday/Yukari/ircClient.py", line 279, in privmsg
    self.factory.handle.recIrcMsg(user, channel, msg)
  File "yukari.py", line 176, in recIrcMsg
    self.wsFactory.prot.relayToCyChat(line)
  File "/home/dd/mikumonday/Yukari/connections/cytube/cyClient.py", line 278, in relayToCyChat
    'args': {'msg': msg, 'meta': {'modflair': modflair}}})
  File "/home/dd/mikumonday/Yukari/connections/cytube/cyClient.py", line 253, in sendf
    json.dumps(fdict.get("args", None)).encode('utf8'))
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
exceptions.UnicodeDecodeError: 'utf8' codec can't decode byte 0x92 in position 144: invalid start byte
